name: 'Cloudinary Upload'
author: 'nichoth'
description: 'Upload your medias with Cloudinary Upload Github Action to Cloudinary.'
branding:
  icon: arrow-up-circle
  color: purple
inputs:
  reset:
    description: 'Remove all assets from the given folder before uploading.'
    required: false
    default: false
  folder:
    description: 'Folder for Cloudinary'
    required: false
  public_id_prefix:
    description: 'An optional filename prefix'
    required: false
  cloud-name:
    description: 'Cloudinary account name'
    required: false
    default: '<name>'
  api-key:
    description: 'Cloudinary API Key'
    required: false
    default: '<api-key>'
  api-secret:
    description: 'Cloudinary API Secret Key'
    required: false
    default: '<api-secret>'
  image:
    description: 'Image path to upload'
    required: false
    default: ""
  images:
    description: 'Pattern or array of images path to upload'
    required: false
    default: ""
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node20'
  main: 'dist/index.js'
